/*

 MAZEMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\tyler\Documents\Gameboycode\Testing\mazesprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mazemap2Width 20
#define mazemap2Height 18
#define mazemap2Bank 0

extern unsigned char mazemap2[];

/* End of MAZEMAP2.H */
