/*

 MAZEMAP4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\tyler\Documents\Gameboycode\Testing\mazesprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MazeMap4Width 20
#define MazeMap4Height 18
#define MazeMap4Bank 0

extern unsigned char MazeMap4[];

/* End of MAZEMAP4.H */
